[package]
edition = "2021"
name    = "vprogs-transaction-runtime-lock"
version = "0.1.0"

[dependencies]
borsh                                           = "1.6.0"
vprogs-transaction-runtime-auth-context         = { path = "../auth-context" }
vprogs-transaction-runtime-builtin-capabilities = { path = "../builtin-capabilities" }
vprogs-transaction-runtime-data                 = { path = "../data" }
vprogs-transaction-runtime-signature-lock       = { path = "../signature-lock" }
