[package]
name = "kas-l2-move-runtime-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
move-core-types = { git = "https://github.com/MystenLabs/sui.git", package = "move-core-types", rev = "0d4ab7d" }
move-binary-format = { git = "https://github.com/MystenLabs/sui.git", package = "move-binary-format", rev = "0d4ab7d" }
move-vm-runtime = { git = "https://github.com/MystenLabs/sui.git", package = "move-vm-runtime", rev = "0d4ab7d" }
move-vm-types = { git = "https://github.com/MystenLabs/sui.git", package = "move-vm-types", rev = "0d4ab7d" }
move-stdlib-natives = { git = "https://github.com/MystenLabs/sui.git", package = "move-stdlib-natives", rev = "0d4ab7d" }
kas-l2-runtime-core = { path = "../../runtime/core" }
kas-l2-storage-manager = { path = "../../storage/manager" }
kas-l2-storage-rocksdb-store = { path = "../../storage/rocksdb-store" }
kas-l2-storage-store-interface = { path = "../../storage/store-interface" }
kas-l2-runtime-state-space = { path = "../../runtime/state-space" }
bcs = "0.1.6"
borsh = "1.5.7"
indexmap = "2.11.0"
anyhow = "1.0.99"
