[package]
name = "kas-l2-vm-interface"
version = "0.1.0"
edition = "2021"

[dependencies]
kas-l2-storage-types = { path = "../../storage/types" }
kas-l2-runtime-state = { path = "../../runtime/state" }
kas-l2-runtime-types = { path = "../../runtime/types" }
kas-l2-vm-crypto = { path = "../crypto" }
borsh = "1.5.7"