[package]
edition = "2021"
name    = "vprogs-storage-manager"
version = "0.1.0"

[dependencies]
crossbeam-queue      = "0.3.12"
crossbeam-utils      = "0.8.21"
vprogs-core-macros   = { path = "../../core/macros" }
vprogs-storage-types = { path = "../types" }
