[package]
edition = "2021"
name    = "kas-l2-vm-program-context"
version = "0.1.0"

[dependencies]
kas-l2-vm-address            = { path = "../address" }
kas-l2-vm-authenticated-data = { path = "../authenticated-data" }
kas-l2-vm-data-context       = { path = "../data-context" }
kas-l2-vm-error              = { path = "../error" }
