[workspace]
resolver = "3"

members = [
  "core/*",
  "move-runtime/*",
  "runtime/*",
  "storage/*",
  "transaction-runtime/*",
  "vm/*",
]

default-members = [
  "core/*",
  "move-runtime/*",
  "runtime/*",
  "storage/*",
  "transaction-runtime/*",
  "vm/*",
]

exclude = []
