[workspace]
resolver = "3"

members = [
    "core/*",
    "move-runtime/*",
    "runtime/*",
    "storage/*",
]

default-members = [
    "core/*",
    "move-runtime/*",
    "runtime/*",
    "storage/*",
]
