[workspace]
resolver = "3"

members = [
  "core/*",
  "node/*",
  "scheduling/*",
  "storage/*",
  "transaction-runtime/*",
]

default-members = [
  "core/*",
  "node/*",
  "scheduling/*",
  "storage/*",
  "transaction-runtime/*",
]

exclude = []
