comment_width               = 100
edition                     = "2024"
format_code_in_doc_comments = true
group_imports               = "StdExternalCrate"
imports_granularity         = "Crate"
max_width                   = 100
normalize_comments          = true
normalize_doc_attributes    = true
struct_lit_width            = 100
struct_variant_width        = 100
style_edition               = "2024"
use_small_heuristics        = "Max"
wrap_comments               = true
