edition = "2024"
style_edition = "2024"
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
normalize_comments = true
normalize_doc_attributes = true
wrap_comments = true
max_width = 100
comment_width = 100
struct_variant_width = 100
struct_lit_width = 100
use_small_heuristics = "Max"