[package]
edition = "2021"
name    = "kas-l2-vm-tx-runtime"
version = "0.1.0"

[dependencies]
kas-l2-runtime-manager        = { path = "../../runtime/manager" }
kas-l2-runtime-state          = { path = "../../runtime/state" }
kas-l2-storage-types          = { path = "../../storage/types" }
kas-l2-vm-error               = { path = "../error" }
kas-l2-vm-lock                = { path = "../lock" }
kas-l2-vm-object-access       = { path = "../object-access" }
kas-l2-vm-object-id           = { path = "../object-id" }
kas-l2-vm-transaction         = { path = "../transaction" }
kas-l2-vm-transaction-context = { path = "../transaction-context" }
kas-l2-vm-transaction-effects = { path = "../transaction-effects" }
