[package]
edition = "2021"
name    = "kas-l2-transaction-runtime-object-id"
version = "0.1.0"

[dependencies]
borsh                              = "1.6.0"
kas-l2-transaction-runtime-address = { path = "../address" }
