[package]
edition = "2021"
name    = "vprogs-transaction-runtime-object-id"
version = "0.1.0"

[dependencies]
borsh                              = "1.6.0"
vprogs-transaction-runtime-address = { path = "../address" }
