[package]
edition = "2021"
name    = "kas-l2-transaction-runtime-transaction"
version = "0.1.0"

[dependencies]
kas-l2-runtime-types                     = { path = "../../runtime/types" }
kas-l2-transaction-runtime-instruction   = { path = "../instruction" }
kas-l2-transaction-runtime-object-access = { path = "../object-access" }
kas-l2-transaction-runtime-object-id     = { path = "../object-id" }
