[package]
edition = "2021"
name    = "vprogs-transaction-runtime-transaction"
version = "0.1.0"

[dependencies]
vprogs-scheduling-types                  = { path = "../../scheduling/types" }
vprogs-transaction-runtime-instruction   = { path = "../instruction" }
vprogs-transaction-runtime-object-access = { path = "../object-access" }
vprogs-transaction-runtime-object-id     = { path = "../object-id" }
