[package]
edition = "2021"
name    = "kas-l2-vm-lock"
version = "0.1.0"

[dependencies]
borsh                          = "1.5.7"
kas-l2-vm-auth-context         = { path = "../auth-context" }
kas-l2-vm-builtin-capabilities = { path = "../builtin-capabilities" }
kas-l2-vm-data                 = { path = "../data" }
kas-l2-vm-signature-lock       = { path = "../signature-lock" }
