[package]
edition = "2021"
name    = "vprogs-transaction-runtime-instruction"
version = "0.1.0"

[dependencies]
vprogs-transaction-runtime-address     = { path = "../address" }
vprogs-transaction-runtime-program-arg = { path = "../program-arg" }
