[package]
edition = "2021"
name    = "kas-l2-transaction-runtime-program-context"
version = "0.1.0"

[dependencies]
kas-l2-transaction-runtime-address            = { path = "../address" }
kas-l2-transaction-runtime-authenticated-data = { path = "../authenticated-data" }
kas-l2-transaction-runtime-data-context       = { path = "../data-context" }
kas-l2-transaction-runtime-error              = { path = "../error" }
