[package]
edition = "2021"
name    = "vprogs-transaction-runtime-builtin-capabilities"
version = "0.1.0"

[dependencies]
vprogs-transaction-runtime-address = { path = "../address" }
vprogs-transaction-runtime-data    = { path = "../data" }
