[package]
name = "kas-l2-vm-builtin-capabilities"
version = "0.1.0"
edition = "2021"

[dependencies]
kas-l2-vm-data = { path = "../data" }
kas-l2-vm-object-id = { path = "../object-id" }
kas-l2-vm-crypto = { path = "../crypto" }
kas-l2-vm-interface = { path = "../interface" }
borsh = "1.5.7"