[package]
edition = "2021"
name    = "vprogs-transaction-runtime-data-context"
version = "0.1.0"

[dependencies]
vprogs-transaction-runtime-address            = { path = "../address" }
vprogs-transaction-runtime-authenticated-data = { path = "../authenticated-data" }
vprogs-transaction-runtime-error              = { path = "../error" }
