[package]
edition = "2021"
name    = "vprogs-core-macros"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.103"
quote       = "1.0.42"
syn         = { version = "2.0.111", features = ["full"] }
