[package]
edition = "2021"
name    = "kas-l2-transaction-runtime"
version = "0.1.0"

[dependencies]
borsh                                          = "1.6.0"
kas-l2-runtime-manager                         = { path = "../../runtime/manager" }
kas-l2-runtime-state                           = { path = "../../runtime/state" }
kas-l2-runtime-types                           = { path = "../../runtime/types" }
kas-l2-storage-types                           = { path = "../../storage/types" }
kas-l2-transaction-runtime-address             = { path = "../address" }
kas-l2-transaction-runtime-auth-context        = { path = "../auth-context" }
kas-l2-transaction-runtime-authenticated-data  = { path = "../authenticated-data" }
kas-l2-transaction-runtime-data                = { path = "../data" }
kas-l2-transaction-runtime-data-context        = { path = "../data-context" }
kas-l2-transaction-runtime-error               = { path = "../error" }
kas-l2-transaction-runtime-instruction         = { path = "../instruction" }
kas-l2-transaction-runtime-lock                = { path = "../lock" }
kas-l2-transaction-runtime-object-id           = { path = "../object-id" }
kas-l2-transaction-runtime-program             = { path = "../program" }
kas-l2-transaction-runtime-pubkey              = { path = "../pubkey" }
kas-l2-transaction-runtime-transaction         = { path = "../transaction" }
kas-l2-transaction-runtime-transaction-effects = { path = "../transaction-effects" }
