[package]
edition = "2021"
name    = "kas-l2-vm-signature-lock"
version = "0.1.0"

[dependencies]
kas-l2-vm-auth-context         = { path = "../auth-context" }
kas-l2-vm-builtin-capabilities = { path = "../builtin-capabilities" }
kas-l2-vm-pubkey               = { path = "../pubkey" }
