[package]
name = "kas-l2-move-runtime-test-suite"
version = "0.1.0"
edition = "2021"

[dependencies]
kas-l2-runtime-execution-dag = { path = "../../runtime/execution-dag" }
kas-l2-storage-rocksdb-store = { path = "../../storage/rocksdb-store" }
kas-l2-runtime-storage-manager = { path = "../../runtime/storage-manager" }
kas-l2-move-runtime-vm = { path = "../vm" }
move-core-types = { git = "https://github.com/MystenLabs/sui.git", rev = "0d4ab7d" }
move-compiler = { git = "https://github.com/MystenLabs/sui.git", rev = "0d4ab7d" }
move-symbol-pool = { git = "https://github.com/MystenLabs/sui.git", rev = "0d4ab7d" }
tempfile = "3.23.0"
anyhow = "1.0.99"
vfs = "0.10.0"
