[package]
name = "kas-l2-vm-object-lock-type"
version = "0.1.0"
edition = "2021"

[dependencies]
kas-l2-vm-builtin-capabilities = { path = "../builtin-capabilities" }
kas-l2-vm-crypto = { path = "../crypto" }
kas-l2-vm-interface = { path = "../interface" }